function GetNFLTeams() as Object
    return {
        "Cardinals": "cardinals", "Arizona Cardinals": "cardinals",
        "Falcons": "falcons", "Atlanta Falcons": "falcons",
        "Ravens": "ravens", "Baltimore Ravens": "ravens",
        "Bills": "bills", "Buffalo Bills": "bills",
        "Panthers": "panthers", "Carolina Panthers": "panthers",
        "Bears": "bears", "Chicago Bears": "bears",
        "Bengals": "bengals", "Cincinnati Bengals": "bengals",
        "Browns": "browns", "Cleveland Browns": "browns",
        "Cowboys": "cowboys", "Dallas Cowboys": "cowboys",
        "Broncos": "broncos", "Denver Broncos": "broncos",
        "Lions": "lions", "Detroit Lions": "lions",
        "Packers": "packers", "Green Bay Packers": "packers",
        "Texans": "texans", "Houston Texans": "texans",
        "Colts": "colts", "Indianapolis Colts": "colts",
        "Jaguars": "jaguars", "Jacksonville Jaguars": "jaguars",
        "Chiefs": "chiefs", "Kansas City Chiefs": "chiefs",
        "Raiders": "raiders", "Las Vegas Raiders": "raiders",
        "Chargers": "chargers", "Los Angeles Chargers": "chargers",
        "Rams": "rams", "Los Angeles Rams": "rams",
        "Dolphins": "dolphins", "Miami Dolphins": "dolphins",
        "Vikings": "vikings", "Minnesota Vikings": "vikings",
        "Patriots": "patriots", "New England Patriots": "patriots",
        "Saints": "saints", "New Orleans Saints": "saints",
        "Giants": "giants", "New York Giants": "giants",
        "Jets": "jets", "New York Jets": "jets",
        "Eagles": "eagles", "Philadelphia Eagles": "eagles",
        "Steelers": "steelers", "Pittsburgh Steelers": "steelers",
        "49ers": "49ers", "San Francisco 49ers": "49ers",
        "Seahawks": "seahawks", "Seattle Seahawks": "seahawks",
        "Buccaneers": "buccaneers", "Tampa Bay Buccaneers": "buccaneers",
        "Titans": "titans", "Tennessee Titans": "titans",
        "Commanders": "commanders", "Washington Commanders": "commanders"
    }
end function

function GetNBATeams() as Object
    return {
        "Hawks": "hawks", "Atlanta Hawks": "hawks",
        "Celtics": "celtics", "Boston Celtics": "celtics",
        "Nets": "nets", "Brooklyn Nets": "nets",
        "Hornets": "hornets", "Charlotte Hornets": "hornets",
        "Bulls": "bulls", "Chicago Bulls": "bulls",
        "Cavaliers": "cavaliers", "Cleveland Cavaliers": "cavaliers",
        "Mavericks": "mavericks", "Dallas Mavericks": "mavericks",
        "Nuggets": "nuggets", "Denver Nuggets": "nuggets",
        "Pistons": "pistons", "Detroit Pistons": "pistons",
        "Warriors": "warriors", "Golden State Warriors": "warriors",
        "Rockets": "rockets", "Houston Rockets": "rockets",
        "Pacers": "pacers", "Indiana Pacers": "pacers",
        "Clippers": "clippers", "LA Clippers": "clippers", "Los Angeles Clippers": "clippers",
        "Lakers": "lakers", "LA Lakers": "lakers", "Los Angeles Lakers": "lakers",
        "Grizzlies": "grizzlies", "Memphis Grizzlies": "grizzlies",
        "Heat": "heat", "Miami Heat": "heat",
        "Bucks": "bucks", "Milwaukee Bucks": "bucks",
        "Timberwolves": "timberwolves", "Minnesota Timberwolves": "timberwolves",
        "Pelicans": "pelicans", "New Orleans Pelicans": "pelicans",
        "Knicks": "knicks", "New York Knicks": "knicks",
        "Thunder": "thunder", "Oklahoma City Thunder": "thunder",
        "Magic": "magic", "Orlando Magic": "magic",
        "76ers": "76ers", "Philadelphia 76ers": "76ers",
        "Suns": "suns", "Phoenix Suns": "suns",
        "Trail Blazers": "trailblazers", "Portland Trail Blazers": "trailblazers",
        "Kings": "kings", "Sacramento Kings": "kings",
        "Spurs": "spurs", "San Antonio Spurs": "spurs",
        "Raptors": "raptors", "Toronto Raptors": "raptors",
        "Jazz": "jazz", "Utah Jazz": "jazz",
        "Wizards": "wizards", "Washington Wizards": "wizards"
    }
end function

function GetMLBTeams() as Object
    return {
        "Diamondbacks": "diamondbacks", "Arizona Diamondbacks": "diamondbacks",
        "Braves": "braves", "Atlanta Braves": "braves",
        "Orioles": "orioles", "Baltimore Orioles": "orioles",
        "Red Sox": "red-sox", "Boston Red Sox": "red-sox",
        "Cubs": "cubs", "Chicago Cubs": "cubs",
        "White Sox": "white-sox", "Chicago White Sox": "white-sox",
        "Reds": "reds", "Cincinnati Reds": "reds",
        "Guardians": "guardians", "Cleveland Guardians": "guardians",
        "Rockies": "rockies", "Colorado Rockies": "rockies",
        "Tigers": "tigers", "Detroit Tigers": "tigers",
        "Astros": "astros", "Houston Astros": "astros",
        "Royals": "royals", "Kansas City Royals": "royals",
        "Angels": "angels", "Los Angeles Angels": "angels",
        "Dodgers": "dodgers", "Los Angeles Dodgers": "dodgers",
        "Marlins": "marlins", "Miami Marlins": "marlins",
        "Brewers": "brewers", "Milwaukee Brewers": "brewers",
        "Twins": "twins", "Minnesota Twins": "twins",
        "Mets": "mets", "New York Mets": "mets",
        "Yankees": "yankees", "New York Yankees": "yankees",
        "Athletics": "athletics", "Oakland Athletics": "athletics",
        "Phillies": "phillies", "Philadelphia Phillies": "phillies",
        "Pirates": "pirates", "Pittsburgh Pirates": "pirates",
        "Padres": "padres", "San Diego Padres": "padres",
        "Giants": "giants", "San Francisco Giants": "giants",
        "Mariners": "mariners", "Seattle Mariners": "mariners",
        "Cardinals": "cardinals", "St. Louis Cardinals": "cardinals",
        "Rays": "rays", "Tampa Bay Rays": "rays",
        "Rangers": "rangers", "Texas Rangers": "rangers",
        "Blue Jays": "blue-jays", "Toronto Blue Jays": "blue-jays",
        "Nationals": "nationals", "Washington Nationals": "nationals"
    }
end function

function GetNHLTeams() as Object
    return {
        "Ducks": "ducks", "Anaheim Ducks": "ducks",
        "Coyotes": "coyotes", "Arizona Coyotes": "coyotes",
        "Bruins": "bruins", "Boston Bruins": "bruins",
        "Sabres": "sabres", "Buffalo Sabres": "sabres",
        "Flames": "flames", "Calgary Flames": "flames",
        "Hurricanes": "hurricanes", "Carolina Hurricanes": "hurricanes",
        "Blackhawks": "blackhawks", "Chicago Blackhawks": "blackhawks",
        "Avalanche": "avalanche", "Colorado Avalanche": "avalanche",
        "Blue Jackets": "blue-jackets", "Columbus Blue Jackets": "blue-jackets",
        "Stars": "stars", "Dallas Stars": "stars",
        "Red Wings": "red-wings", "Detroit Red Wings": "red-wings",
        "Oilers": "oilers", "Edmonton Oilers": "oilers",
        "Panthers": "panthers", "Florida Panthers": "panthers",
        "Kings": "kings", "Los Angeles Kings": "kings",
        "Wild": "wild", "Minnesota Wild": "wild",
        "Canadiens": "canadiens", "Montreal Canadiens": "canadiens",
        "Predators": "predators", "Nashville Predators": "predators",
        "Devils": "devils", "New Jersey Devils": "devils",
        "Islanders": "islanders", "New York Islanders": "islanders",
        "Rangers": "rangers", "New York Rangers": "rangers",
        "Senators": "senators", "Ottawa Senators": "senators",
        "Flyers": "flyers", "Philadelphia Flyers": "flyers",
        "Penguins": "penguins", "Pittsburgh Penguins": "penguins",
        "Sharks": "sharks", "San Jose Sharks": "sharks",
        "Kraken": "kraken", "Seattle Kraken": "kraken",
        "Blues": "blues", "St. Louis Blues": "blues",
        "Lightning": "lightning", "Tampa Bay Lightning": "lightning",
        "Maple Leafs": "maple-leafs", "Toronto Maple Leafs": "maple-leafs",
        "Canucks": "canucks", "Vancouver Canucks": "canucks",
        "Golden Knights": "golden-knights", "Vegas Golden Knights": "golden-knights",
        "Capitals": "capitals", "Washington Capitals": "capitals",
        "Jets": "jets", "Winnipeg Jets": "jets",
        "Mammoth": "mammoth", "Utah Mammoth": "mammoth"
    }
end function

function GetNCAATeams() as Object
    return {
        "Tennessee": "tennessee", "Tennessee Volunteers": "tennessee", "TENN": "tennessee", "Vols": "tennessee",
        "Texas A&M": "texas-am", "Texas A&M Aggies": "texas-am", "TA&M": "texas-am", "Texas AM": "texas-am",
        "Texas": "texas", "Texas Longhorns": "texas", "TEX": "texas",
        "Texas State": "texas-state", "Texas State Bobcats": "texas-state", "TXST": "texas-state",
        "Texas Tech": "texas-tech", "Texas Tech Red Raiders": "texas-tech", "TTU": "texas-tech",
        "Kansas State": "kansas-state", "Kansas State Wildcats": "kansas-state", "K-State": "kansas-state", "KSU": "kansas-state",
        "Kansas": "kansas", "Kansas Jayhawks": "kansas", "KU": "kansas",
        "Miami (OH)": "miami-oh", "Miami (OH) RedHawks": "miami-oh", "Miami OH": "miami-oh",
        "Miami": "miami", "Miami Hurricanes": "miami",
        "Florida State": "florida-state", "Florida State Seminoles": "florida-state", "FSU": "florida-state", "Florida St": "florida-state",
        "Florida Atlantic": "florida-atlantic", "Florida Atlantic Owls": "florida-atlantic", "FAU": "florida-atlantic",
        "Florida International": "florida-international", "Florida International Panthers": "florida-international", "FIU": "florida-international",
        "Florida": "florida", "Florida Gators": "florida",
        "North Carolina": "north-carolina", "North Carolina Tar Heels": "north-carolina", "UNC": "north-carolina", "North Carolina A&T": "north-carolina",
        "NC State": "nc-state", "NC State Wolfpack": "nc-state", "NC St": "nc-state", "NCST": "nc-state",
        "Air Force": "air-force", "Air Force Falcons": "air-force",
        "Akron": "akron", "Akron Zips": "akron",
        "Alabama": "alabama", "Alabama Crimson Tide": "alabama",
        "App State": "appalachian-state", "Appalachian State": "appalachian-state", "Appalachian State Mountaineers": "appalachian-state",
        "Arizona": "arizona", "Arizona Wildcats": "arizona",
        "Arizona State": "arizona-state", "Arizona State Sun Devils": "arizona-state", "ASU": "arizona-state",
        "Arkansas": "arkansas", "Arkansas Razorbacks": "arkansas",
        "Arkansas State": "arkansas-state", "Arkansas State Red Wolves": "arkansas-state",
        "Army": "army", "Army Black Knights": "army",
        "Auburn": "auburn", "Auburn Tigers": "auburn",
        "Ball State": "ball-state", "Ball State Cardinals": "ball-state",
        "Baylor": "baylor", "Baylor Bears": "baylor",
        "Boise State": "boise-state", "Boise State Broncos": "boise-state", "Boise St": "boise-state",
        "Boston College": "boston-college", "Boston College Eagles": "boston-college", "BC": "boston-college",
        "Bowling Green": "bowling-green", "Bowling Green Falcons": "bowling-green", "BGSU": "bowling-green",
        "Buffalo": "buffalo", "Buffalo Bulls": "buffalo",
        "BYU": "byu", "BYU Cougars": "byu",
        "California": "california", "California Golden Bears": "california", "Cal": "california",
        "Central Michigan": "central-michigan", "Central Michigan Chippewas": "central-michigan", "CMU": "central-michigan",
        "Charlotte": "charlotte", "Charlotte 49ers": "charlotte",
        "Cincinnati": "cincinnati", "Cincinnati Bearcats": "cincinnati", "Cincy": "cincinnati",
        "Clemson": "clemson", "Clemson Tigers": "clemson",
        "Coastal Carolina": "coastal-carolina", "Coastal Carolina Chanticleers": "coastal-carolina", "CCU": "coastal-carolina",
        "Colorado": "colorado", "Colorado Buffaloes": "colorado",
        "Colorado State": "colorado-state", "Colorado State Rams": "colorado-state", "CSU": "colorado-state",
        "Connecticut": "connecticut", "Connecticut Huskies": "connecticut", "UConn": "connecticut",
        "Duke": "duke", "Duke Blue Devils": "duke",
        "East Carolina": "east-carolina", "East Carolina Pirates": "east-carolina", "ECU": "east-carolina",
        "Eastern Michigan": "eastern-michigan", "Eastern Michigan Eagles": "eastern-michigan", "EMU": "eastern-michigan",
        "Fresno State": "fresno-state", "Fresno State Bulldogs": "fresno-state", "Fresno St": "fresno-state",
        "Georgia": "georgia", "Georgia Bulldogs": "georgia", "UGA": "georgia",
        "Georgia Southern": "georgia-southern", "Georgia Southern Eagles": "georgia-southern", "Ga Southern": "georgia-southern",
        "Georgia State": "georgia-state", "Georgia State Panthers": "georgia-state", "Ga State": "georgia-state",
        "Georgia Tech": "georgia-tech", "Georgia Tech Yellow Jackets": "georgia-tech", "GT": "georgia-tech",
        "Hawai'i": "hawaii", "Hawai'i Rainbow Warriors": "hawaii", "Hawaii": "hawaii",
        "Houston": "houston", "Houston Cougars": "houston",
        "Illinois": "illinois", "Illinois Fighting Illini": "illinois",
        "Indiana": "indiana", "Indiana Hoosiers": "indiana",
        "Iowa": "iowa", "Iowa Hawkeyes": "iowa",
        "Iowa State": "iowa-state", "Iowa State Cyclones": "iowa-state", "ISU": "iowa-state",
        "James Madison": "james-madison", "James Madison Dukes": "james-madison", "JMU": "james-madison",
        "Kent State": "kent-state", "Kent State Golden Flashes": "kent-state", "Kent St": "kent-state",
        "Kentucky": "kentucky", "Kentucky Wildcats": "kentucky", "UK": "kentucky",
        "Liberty": "liberty", "Liberty Flames": "liberty",
        "Louisiana": "louisiana", "Louisiana Ragin' Cajuns": "louisiana", "UL": "louisiana",
        "Louisiana Monroe": "louisiana-monroe", "Louisiana Monroe Warhawks": "louisiana-monroe", "ULM": "louisiana-monroe",
        "Louisiana Tech": "louisiana-tech", "Louisiana Tech Bulldogs": "louisiana-tech", "LA Tech": "louisiana-tech",
        "Louisville": "louisville", "Louisville Cardinals": "louisville", "Lou": "louisville",
        "LSU": "lsu", "LSU Tigers": "lsu",
        "Marshall": "marshall", "Marshall Thundering Herd": "marshall",
        "Maryland": "maryland", "Maryland Terrapins": "maryland", "MD": "maryland",
        "Memphis": "memphis", "Memphis Tigers": "memphis",
        "Middle Tennessee": "middle-tennessee", "Middle Tennessee Blue Raiders": "middle-tennessee", "MTSU": "middle-tennessee",
        "Minnesota": "minnesota", "Minnesota Golden Gophers": "minnesota", "Minn": "minnesota",
        "Mississippi State": "mississippi-state", "Mississippi State Bulldogs": "mississippi-state", "Miss St": "mississippi-state", "MSST": "mississippi-state",
        "Missouri": "missouri", "Missouri Tigers": "missouri", "Mizzou": "missouri", "MIZZ": "missouri",
        "Navy": "navy", "Navy Midshipmen": "navy",
        "Nebraska": "nebraska", "Nebraska Cornhuskers": "nebraska", "Neb": "nebraska",
        "Nevada": "nevada", "Nevada Wolf Pack": "nevada", "NV": "nevada",
        "New Mexico": "new-mexico", "New Mexico Lobos": "new-mexico", "UNM": "new-mexico",
        "New Mexico State": "new-mexico-state", "New Mexico State Aggies": "new-mexico-state", "NM State": "new-mexico-state", "NMST": "new-mexico-state",
        "North Texas": "north-texas", "North Texas Mean Green": "north-texas", "UNT": "north-texas",
        "Northern Illinois": "northern-illinois", "Northern Illinois Huskies": "northern-illinois", "NIU": "northern-illinois",
        "Northwestern": "northwestern", "Northwestern Wildcats": "northwestern", "NW": "northwestern",
        "Notre Dame": "notre-dame", "Notre Dame Fighting Irish": "notre-dame", "ND": "notre-dame",
        "Ohio": "ohio", "Ohio Bobcats": "ohio",
        "Ohio State": "ohio-state", "Ohio State Buckeyes": "ohio-state", "OSU": "ohio-state",
        "Oklahoma": "oklahoma", "Oklahoma Sooners": "oklahoma", "OU": "oklahoma", "OKLA": "oklahoma",
        "Oklahoma State": "oklahoma-state", "Oklahoma State Cowboys": "oklahoma-state", "OK State": "oklahoma-state", "OKST": "oklahoma-state",
        "Old Dominion": "old-dominion", "Old Dominion Monarchs": "old-dominion", "ODU": "old-dominion",
        "Ole Miss": "ole-miss", "Ole Miss Rebels": "ole-miss", "MISS": "ole-miss",
        "Oregon": "oregon", "Oregon Ducks": "oregon", "ORE": "oregon",
        "Oregon State": "oregon-state", "Oregon State Beavers": "oregon-state", "ORST": "oregon-state",
        "Penn State": "penn-state", "Penn State Nittany Lions": "penn-state", "PSU": "penn-state",
        "Pittsburgh": "pittsburgh", "Pittsburgh Panthers": "pittsburgh", "Pitt": "pittsburgh", "PITT": "pittsburgh",
        "Purdue": "purdue", "Purdue Boilermakers": "purdue", "PUR": "purdue",
        "Rice": "rice", "Rice Owls": "rice",
        "Rutgers": "rutgers", "Rutgers Scarlet Knights": "rutgers", "RUTG": "rutgers",
        "Sam Houston": "sam-houston", "Sam Houston Bearkats": "sam-houston", "SAM": "sam-houston",
        "San Diego State": "san-diego-state", "San Diego State Aztecs": "san-diego-state", "SDSU": "san-diego-state", "SD State": "san-diego-state",
        "San Jose State": "san-jose-state", "San Jose State Spartans": "san-jose-state", "SJSU": "san-jose-state",
        "SMU": "smu", "SMU Mustangs": "smu",
        "South Alabama": "south-alabama", "South Alabama Jaguars": "south-alabama", "USA": "south-alabama",
        "South Carolina": "south-carolina", "South Carolina Gamecocks": "south-carolina", "SC": "south-carolina",
        "South Florida": "south-florida", "South Florida Bulls": "south-florida", "USF": "south-florida",
        "Southern Miss": "southern-miss", "Southern Miss Golden Eagles": "southern-miss", "USM": "southern-miss",
        "Stanford": "stanford", "Stanford Cardinal": "stanford", "STAN": "stanford",
        "Syracuse": "syracuse", "Syracuse Orange": "syracuse", "SYR": "syracuse",
        "TCU": "tcu", "TCU Horned Frogs": "tcu",
        "Temple": "temple", "Temple Owls": "temple", "TEM": "temple",
        "Toledo": "toledo", "Toledo Rockets": "toledo", "TOL": "toledo",
        "Troy": "troy", "Troy Trojans": "troy", "TROY": "troy",
        "Tulane": "tulane", "Tulane Green Wave": "tulane", "TULANE": "tulane",
        "Tulsa": "tulsa", "Tulsa Golden Hurricane": "tulsa", "TULSA": "tulsa",
        "UAB": "uab", "UAB Blazers": "uab",
        "UCF": "ucf", "UCF Knights": "ucf",
        "UCLA": "ucla", "UCLA Bruins": "ucla",
        "UMass": "umass", "UMass Minutemen": "umass", "UMASS": "umass",
        "UNLV": "unlv", "UNLV Rebels": "unlv",
        "USC": "usc", "USC Trojans": "usc",
        "Utah": "utah", "Utah Utes": "utah", "UTAH": "utah",
        "Utah State": "utah-state", "Utah State Aggies": "utah-state", "USU": "utah-state",
        "UTEP": "utep", "UTEP Miners": "utep",
        "UTSA": "utsa", "UTSA Roadrunners": "utsa",
        "Vanderbilt": "vanderbilt", "Vanderbilt Commodores": "vanderbilt", "VAN": "vanderbilt",
        "Virginia": "virginia", "Virginia Cavaliers": "virginia", "UVA": "virginia",
        "Virginia Tech": "virginia-tech", "Virginia Tech Hokies": "virginia-tech", "VT": "virginia-tech",
        "Wake Forest": "wake-forest", "Wake Forest Demon Deacons": "wake-forest", "WF": "wake-forest",
        "Washington": "washington", "Washington Huskies": "washington", "WASH": "washington",
        "Washington State": "washington-state", "Washington State Cougars": "washington-state", "WSU": "washington-state",
        "West Virginia": "west-virginia", "West Virginia Mountaineers": "west-virginia", "WVU": "west-virginia",
        "Western Kentucky": "western-kentucky", "Western Kentucky Hilltoppers": "western-kentucky", "WKU": "western-kentucky",
        "Western Michigan": "western-michigan", "Western Michigan Broncos": "western-michigan", "WMU": "western-michigan",
        "Wisconsin": "wisconsin", "Wisconsin Badgers": "wisconsin", "WIS": "wisconsin",
        "Wyoming": "wyoming", "Wyoming Cowboys": "wyoming", "WYO": "wyoming"
    }
end function

function GetNFLAbbrs() as Object
    return {
        "Cardinals": "ari", "Arizona Cardinals": "ari",
        "Falcons": "atl", "Atlanta Falcons": "atl",
        "Ravens": "bal", "Baltimore Ravens": "bal",
        "Bills": "buf", "Buffalo Bills": "buf",
        "Panthers": "car", "Carolina Panthers": "car",
        "Bears": "chi", "Chicago Bears": "chi",
        "Bengals": "cin", "Cincinnati Bengals": "cin",
        "Browns": "cle", "Cleveland Browns": "cle",
        "Cowboys": "dal", "Dallas Cowboys": "dal",
        "Broncos": "den", "Denver Broncos": "den",
        "Lions": "det", "Detroit Lions": "det",
        "Packers": "gb", "Green Bay Packers": "gb",
        "Texans": "hou", "Houston Texans": "hou",
        "Colts": "ind", "Indianapolis Colts": "ind",
        "Jaguars": "jax", "Jacksonville Jaguars": "jax",
        "Chiefs": "kc", "Kansas City Chiefs": "kc",
        "Raiders": "lv", "Las Vegas Raiders": "lv",
        "Chargers": "lac", "Los Angeles Chargers": "lac",
        "Rams": "lar", "Los Angeles Rams": "lar",
        "Dolphins": "mia", "Miami Dolphins": "mia",
        "Vikings": "min", "Minnesota Vikings": "min",
        "Patriots": "ne", "New England Patriots": "ne",
        "Saints": "no", "New Orleans Saints": "no",
        "Giants": "nyg", "New York Giants": "nyg",
        "Jets": "nyj", "New York Jets": "nyj",
        "Eagles": "phi", "Philadelphia Eagles": "phi",
        "Steelers": "pit", "Pittsburgh Steelers": "pit",
        "49ers": "sf", "San Francisco 49ers": "sf",
        "Seahawks": "sea", "Seattle Seahawks": "sea",
        "Buccaneers": "tb", "Tampa Bay Buccaneers": "tb",
        "Titans": "ten", "Tennessee Titans": "ten",
        "Commanders": "wsh", "Washington Commanders": "wsh"
    }
end function

function GetNBAAbbrs() as Object
    return {
        "Hawks": "atl", "Atlanta Hawks": "atl",
        "Celtics": "bos", "Boston Celtics": "bos",
        "Nets": "bkn", "Brooklyn Nets": "bkn",
        "Hornets": "cha", "Charlotte Hornets": "cha",
        "Bulls": "chi", "Chicago Bulls": "chi",
        "Cavaliers": "cle", "Cleveland Cavaliers": "cle",
        "Mavericks": "dal", "Dallas Mavericks": "dal",
        "Nuggets": "den", "Denver Nuggets": "den",
        "Pistons": "det", "Detroit Pistons": "det",
        "Warriors": "gs", "Golden State Warriors": "gs",
        "Rockets": "hou", "Houston Rockets": "hou",
        "Pacers": "ind", "Indiana Pacers": "ind",
        "Clippers": "lac", "LA Clippers": "lac", "Los Angeles Clippers": "lac",
        "Lakers": "lal", "LA Lakers": "lal", "Los Angeles Lakers": "lal",
        "Grizzlies": "mem", "Memphis Grizzlies": "mem",
        "Heat": "mia", "Miami Heat": "mia",
        "Bucks": "mil", "Milwaukee Bucks": "mil",
        "Timberwolves": "min", "Minnesota Timberwolves": "min",
        "Pelicans": "no", "New Orleans Pelicans": "no",
        "Knicks": "ny", "New York Knicks": "ny",
        "Thunder": "okc", "Oklahoma City Thunder": "okc",
        "Magic": "orl", "Orlando Magic": "orl",
        "76ers": "phi", "Philadelphia 76ers": "phi",
        "Suns": "phx", "Phoenix Suns": "phx",
        "Trail Blazers": "por", "Portland Trail Blazers": "por",
        "Kings": "sac", "Sacramento Kings": "sac",
        "Spurs": "sa", "San Antonio Spurs": "sa",
        "Raptors": "tor", "Toronto Raptors": "tor",
        "Jazz": "utah", "Utah Jazz": "utah",
        "Wizards": "wsh", "Washington Wizards": "wsh"
    }
end function

function GetMLBAbbrs() as Object
    return {
        "Diamondbacks": "ari", "Arizona Diamondbacks": "ari",
        "Braves": "atl", "Atlanta Braves": "atl",
        "Orioles": "bal", "Baltimore Orioles": "bal",
        "Red Sox": "bos", "Boston Red Sox": "bos",
        "Cubs": "chc", "Chicago Cubs": "chc",
        "White Sox": "chw", "Chicago White Sox": "chw",
        "Reds": "cin", "Cincinnati Reds": "cin",
        "Guardians": "cle", "Cleveland Guardians": "cle",
        "Rockies": "col", "Colorado Rockies": "col",
        "Tigers": "det", "Detroit Tigers": "det",
        "Astros": "hou", "Houston Astros": "hou",
        "Royals": "kc", "Kansas City Royals": "kc",
        "Angels": "laa", "Los Angeles Angels": "laa",
        "Dodgers": "lad", "Los Angeles Dodgers": "lad",
        "Marlins": "mia", "Miami Marlins": "mia",
        "Brewers": "mil", "Milwaukee Brewers": "mil",
        "Twins": "min", "Minnesota Twins": "min",
        "Mets": "nym", "New York Mets": "nym",
        "Yankees": "nyy", "New York Yankees": "nyy",
        "Athletics": "ath", "Oakland Athletics": "ath",
        "Phillies": "phi", "Philadelphia Phillies": "phi",
        "Pirates": "pit", "Pittsburgh Pirates": "pit",
        "Padres": "sd", "San Diego Padres": "sd",
        "Giants": "sf", "San Francisco Giants": "sf",
        "Mariners": "sea", "Seattle Mariners": "sea",
        "Cardinals": "stl", "St. Louis Cardinals": "stl",
        "Rays": "tb", "Tampa Bay Rays": "tb",
        "Rangers": "tex", "Texas Rangers": "tex",
        "Blue Jays": "tor", "Toronto Blue Jays": "tor",
        "Nationals": "wsh", "Washington Nationals": "wsh"
    }
end function

function GetNHLAbbrs() as Object
    return {
        "Ducks": "ana", "Anaheim Ducks": "ana",
        "Coyotes": "ari", "Arizona Coyotes": "ari",
        "Bruins": "bos", "Boston Bruins": "bos",
        "Sabres": "buf", "Buffalo Sabres": "buf",
        "Flames": "cgy", "Calgary Flames": "cgy",
        "Hurricanes": "car", "Carolina Hurricanes": "car",
        "Blackhawks": "chi", "Chicago Blackhawks": "chi",
        "Avalanche": "col", "Colorado Avalanche": "col",
        "Blue Jackets": "cbj", "Columbus Blue Jackets": "cbj",
        "Stars": "dal", "Dallas Stars": "dal",
        "Red Wings": "det", "Detroit Red Wings": "det",
        "Oilers": "edm", "Edmonton Oilers": "edm",
        "Panthers": "fla", "Florida Panthers": "fla",
        "Kings": "la", "Los Angeles Kings": "la",
        "Wild": "min", "Minnesota Wild": "min",
        "Canadiens": "mtl", "Montreal Canadiens": "mtl",
        "Predators": "nsh", "Nashville Predators": "nsh",
        "Devils": "njd", "New Jersey Devils": "njd",
        "Islanders": "nyi", "New York Islanders": "nyi",
        "Rangers": "nyr", "New York Rangers": "nyr",
        "Senators": "ott", "Ottawa Senators": "ott",
        "Flyers": "phi", "Philadelphia Flyers": "phi",
        "Penguins": "pit", "Pittsburgh Penguins": "pit",
        "Sharks": "sj", "San Jose Sharks": "sj",
        "Kraken": "sea", "Seattle Kraken": "sea",
        "Blues": "stl", "St. Louis Blues": "stl",
        "Lightning": "tb", "Tampa Bay Lightning": "tb",
        "Maple Leafs": "tor", "Toronto Maple Leafs": "tor",
        "Canucks": "van", "Vancouver Canucks": "van",
        "Golden Knights": "vgk", "Vegas Golden Knights": "vgk",
        "Capitals": "wsh", "Washington Capitals": "wsh",
        "Jets": "wpg", "Winnipeg Jets": "wpg",
        "Mammoth": "utah", "Utah Mammoth": "utah"
    }
end function

function GetNCAATeamId(teamCode as String) as String
    ' Map team codes to ESPN numeric IDs from the gist
    idMap = {
        "air-force": "2005",
        "akron": "2006",
        "alabama": "333",
        "appalachian-state": "2026",
        "arizona": "12",
        "arizona-state": "9",
        "arkansas": "8",
        "arkansas-state": "2032",
        "army": "349",
        "auburn": "2",
        "ball-state": "2050",
        "baylor": "239",
        "boise-state": "68",
        "boston-college": "103",
        "bowling-green": "189",
        "buffalo": "2084",
        "byu": "252",
        "california": "25",
        "central-michigan": "2117",
        "charlotte": "2429",
        "cincinnati": "2132",
        "clemson": "228",
        "coastal-carolina": "324",
        "colorado": "38",
        "colorado-state": "36",
        "connecticut": "41",
        "duke": "150",
        "east-carolina": "151",
        "eastern-michigan": "2199",
        "florida": "57",
        "florida-atlantic": "2226",
        "florida-international": "2229",
        "florida-state": "52",
        "fresno-state": "278",
        "georgia": "61",
        "georgia-southern": "290",
        "georgia-state": "2247",
        "georgia-tech": "59",
        "hawaii": "62",
        "houston": "248",
        "illinois": "356",
        "indiana": "84",
        "iowa": "2294",
        "iowa-state": "66",
        "james-madison": "256",
        "kansas": "2305",
        "kansas-state": "2306",
        "kent-state": "2309",
        "kentucky": "96",
        "liberty": "2335",
        "louisiana": "309",
        "louisiana-monroe": "2433",
        "louisiana-tech": "2348",
        "louisville": "97",
        "lsu": "99",
        "marshall": "276",
        "maryland": "120",
        "memphis": "235",
        "miami": "2390",
        "miami-oh": "193",
        "michigan": "130",
        "michigan-state": "127",
        "middle-tennessee": "2393",
        "minnesota": "135",
        "mississippi-state": "344",
        "missouri": "142",
        "navy": "2426",
        "nc-state": "152",
        "nebraska": "158",
        "nevada": "2440",
        "new-mexico": "167",
        "new-mexico-state": "166",
        "north-carolina": "153",
        "north-texas": "249",
        "northern-illinois": "2459",
        "northwestern": "77",
        "notre-dame": "87",
        "ohio": "195",
        "ohio-state": "194",
        "oklahoma": "201",
        "oklahoma-state": "197",
        "old-dominion": "295",
        "ole-miss": "145",
        "oregon": "2483",
        "oregon-state": "204",
        "penn-state": "213",
        "pittsburgh": "221",
        "purdue": "2509",
        "rice": "242",
        "rutgers": "164",
        "sam-houston": "2534",
        "san-diego-state": "21",
        "san-jose-state": "23",
        "smu": "2567",
        "south-alabama": "6",
        "south-carolina": "2579",
        "south-florida": "58",
        "southern-miss": "2582",
        "stanford": "24",
        "syracuse": "183",
        "tcu": "2628",
        "temple": "218",
        "tennessee": "2633",
        "texas": "251",
        "texas-am": "245",
        "texas-state": "326",
        "texas-tech": "2641",
        "toledo": "2649",
        "troy": "2653",
        "tulane": "2655",
        "tulsa": "202",
        "uab": "5",
        "ucf": "2116",
        "ucla": "26",
        "umass": "113",
        "unlv": "2439",
        "usc": "30",
        "utah": "254",
        "utah-state": "328",
        "utep": "2638",
        "utsa": "2636",
        "vanderbilt": "238",
        "virginia": "258",
        "virginia-tech": "259",
        "wake-forest": "154",
        "washington": "264",
        "washington-state": "265",
        "west-virginia": "277",
        "western-kentucky": "98",
        "western-michigan": "2711",
        "wisconsin": "275",
        "wyoming": "2750"
    }

    if idMap.doesExist(teamCode)
        return idMap[teamCode]
    end if

    return ""
end function

function GetTeamCodeByLeague(teamName as String, league as String) as Dynamic
    ' Force specific matches for ambiguous names
    if LCase(teamName).Instr("texas a") >= 0 or LCase(teamName).Instr("texas am") >= 0 then return "texas-am"
    if LCase(teamName) = "texas" and league = "NCAA" then return "texas"

    teams = invalid
    if league = "NFL" then teams = GetNFLTeams()
    if league = "NBA" then teams = GetNBATeams()
    if league = "MLB" then teams = GetMLBTeams()
    if league = "NHL" then teams = GetNHLTeams()
    if league = "NCAA" then teams = GetNCAATeams()

    if teams = invalid then return invalid

    for each key in teams
        if LCase(teamName).Instr(LCase(key)) >= 0 then return teams[key]
    end for

    return invalid
end function

function GetESPNAbbrByLeague(teamName as String, league as String) as Dynamic
    teams = invalid
    if league = "NFL" then teams = GetNFLAbbrs()
    if league = "NBA" then teams = GetNBAAbbrs()
    if league = "MLB" then teams = GetMLBAbbrs()
    if league = "NHL" then teams = GetNHLAbbrs()

    if teams = invalid then return invalid

    for each key in teams
        if teamName.Instr(key) >= 0 then return teams[key]
    end for
    return invalid
end function